DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<watch_buttons() done, defined at nixie.py:152> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 156, in watch_buttons
    while nixie.button_L_state():
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<watch_buttons() done, defined at nixie.py:152> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 156, in watch_buttons
    while nixie.button_L_state():
  File "/mnt/c/Users/kurowska/GIT/nixie/nixie/nixie_stub.py", line 28, in button_L_state
    def button_L_state(self):
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<watch_buttons() done, defined at nixie.py:152> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 156, in watch_buttons
    while nixie.button_L_state():
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<watch_buttons() done, defined at nixie.py:152> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 156, in watch_buttons
    while nixie.button_L_state():
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<watch_buttons() done, defined at nixie.py:152> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 156, in watch_buttons
    while nixie.button_L_state():
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<showoff() done, defined at nixie.py:100> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 103, in showoff
    if mode == "Showoff":
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<showoff() done, defined at nixie.py:100> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 103, in showoff
    if mode == "Showoff":
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<showoff() done, defined at nixie.py:100> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 103, in showoff
    if mode == "Showoff":
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6' coro=<showoff() done, defined at nixie.py:100> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "nixie.py", line 167, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "nixie.py", line 103, in showoff
    if mode == "Showoff":
KeyboardInterrupt
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
